# Generated by Django 4.1.2 on 2022-10-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Tiers',
        ),
    ]
