# Generated by Django 4.1.2 on 2022-10-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_detail',
            name='account_detail',
        ),
        migrations.RemoveField(
            model_name='account_detail',
            name='products',
        ),
        migrations.RemoveField(
            model_name='account_detail',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='account_detail',
            name='tiers',
        ),
        migrations.AddField(
            model_name='account_detail',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
